[package]
name = "spv"
version = "0.1.0"
authors = ["Theo Gilbert"]
edition = "2018"
description = "Command line utility to supervize resource usage across processes"
license = "Apache-2.0"

[dependencies]
