[package]
name = "spv"
version = "0.1.0"
authors = ["Theo Gilbert"]
edition = "2018"
description = "Command line utility to supervize resource usage of processes"
license = "Apache-2.0"

[dependencies]
tui = "0.10.0"
termion = "1.5.5"

[dev-dependencies]
tempfile = "3.1.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3