name: CI

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ '*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update rustup
      run: rustup update stable
    - name: Build
      run: cargo build --all-features

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update rustup
      run: rustup update stable
    - name: Run tests
      run: cargo test --all-features

  rustfmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update rustup
      run: rustup update stable
    - name: Check format
      run: cargo fmt --all -- --check